# Extract csv file data

In [1]:
import pandas as pd
data=pd.read_excel('district_wise.xls',index_col="State_Code")
rows=data.loc["DL"]
#print(type[rows])
rows

,SlNo,State,District_Key,District,Confirmed,Active,Recovered,Deceased,Migrated_Other,Delta_Confirmed,Delta_Active,Delta_Recovered,Delta_Deceased,District_Notes,Last_Updated
State_Code,,,,,,,,,,,,,,,
DL,144,Delhi,DL_Central Delhi,Central Delhi,184,184,0,0,0,0,0,0,0,NaN,NaN
DL,145,Delhi,DL_East Delhi,East Delhi,38,38,0,0,0,0,0,0,0,NaN,NaN
DL,146,Delhi,DL_New Delhi,New Delhi,37,37,0,0,0,0,0,0,0,NaN,NaN
DL,147,Delhi,DL_North Delhi,North Delhi,60,60,0,0,0,0,0,0,0,NaN,NaN
DL,148,Delhi,DL_North East Delhi,North East Delhi,25,25,0,0,0,0,0,0,0,NaN,NaN
DL,149,Delhi,DL_North West Delhi,North West Delhi,32,31,0,1,0,0,0,0,0,NaN,NaN
DL,150,Delhi,DL_Shahdara,Shahdara,48,48,0,0,0,0,0,0,0,NaN,NaN
DL,151,Delhi,DL_South Delhi,South Delhi,70,70,0,0,0,0,0,0,0,NaN,NaN
DL,152,Delhi,DL_South East Delhi,South East Delhi,130,130,0,0,0,0,0,0,0,NaN,NaN
DL,153,Delhi,DL_South West Delhi,South West Delhi,42,42,0,0,0,0,0,0,0,NaN,NaN
DL,154,Delhi,DL_West Delhi,West Delhi,122,122,0,0,0,0,0,0,0,NaN,NaN
DL,737,Delhi,DL_Unknown,Unknown,98656,24251,71339,3066,0,0,0,0,0,NaN,NaN

In [ ]:
EXTRACT EXCEL DATA

In [1]:
import pandas as pd
data=pd.read_csv('district_wise.csv',index_col="State_Code")
rows=data.loc["DL"]
#print(type[rows])
rows

,SlNo,State,District_Key,District,Confirmed,Active,Recovered,Deceased,Migrated_Other,Delta_Confirmed,Delta_Active,Delta_Recovered,Delta_Deceased,District_Notes,Last_Updated
State_Code,,,,,,,,,,,,,,,
DL,144,Delhi,DL_Central Delhi,Central Delhi,184,184,0,0,0,0,0,0,0,NaN,NaN
DL,145,Delhi,DL_East Delhi,East Delhi,38,38,0,0,0,0,0,0,0,NaN,NaN
DL,146,Delhi,DL_New Delhi,New Delhi,37,37,0,0,0,0,0,0,0,NaN,NaN
DL,147,Delhi,DL_North Delhi,North Delhi,60,60,0,0,0,0,0,0,0,NaN,NaN
DL,148,Delhi,DL_North East Delhi,North East Delhi,25,25,0,0,0,0,0,0,0,NaN,NaN
DL,149,Delhi,DL_North West Delhi,North West Delhi,32,31,0,1,0,0,0,0,0,NaN,NaN
DL,150,Delhi,DL_Shahdara,Shahdara,48,48,0,0,0,0,0,0,0,NaN,NaN
DL,151,Delhi,DL_South Delhi,South Delhi,70,70,0,0,0,0,0,0,0,NaN,NaN
DL,152,Delhi,DL_South East Delhi,South East Delhi,130,130,0,0,0,0,0,0,0,NaN,NaN
DL,153,Delhi,DL_South West Delhi,South West Delhi,42,42,0,0,0,0,0,0,0,NaN,NaN
DL,154,Delhi,DL_West Delhi,West Delhi,122,122,0,0,0,0,0,0,0,NaN,NaN
DL,737,Delhi,DL_Unknown,Unknown,98656,24251,71339,3066,0,0,0,0,0,NaN,NaN